steps:
  - id: 'Deploy pre-built version'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: gsutil
    args:
      [
        '-m',
        'rsync',
        '-d',
        '-r',
        'gs://gr4vy-embed-cdn-version-repository/${COMMIT_SHA}',
        'gs://$_ARTIFACT_STORAGE_BUCKET/',
      ]

  - id: 'Invalidate CDN cache'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: ash
    args:
      - '-c'
      - >-
        gcloud compute url-maps invalidate-cdn-cache $_URL_MAP --path='/*' --async --project $PROJECT_ID

substitutions:
  _GR4VY_ID: ${PROJECT_ID%-*}
  _ARTIFACT_STORAGE_BUCKET: embed-cdn-${_GR4VY_ID}-gr4vy-app
  _URL_MAP: embed-cdn-${_GR4VY_ID}-gr4vy-app-url-map

options:
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
