version: '3.8'

services:
  dev:
    # Use the local Dockerfile
    build:
      context: .
    # Mount the code, and most notably also mount 
    # the node modules seperately
    volumes:
      - .:/code:rw
      - node_modules:/code/node_modules
    # Expose the storybook and dev ports
    ports:
      - 8081:8081
      - 6007:6007
    # Show colors in the log output
    tty: yes

# Using a docker volume for node modules
volumes:
  node_modules: