name: CI

on:
  push: {}
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Lint the content
      run: |
        yarn install
        yarn lint
        yarn test

  push-storybook:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [14.x]

    needs:
      - lint

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Compile the content
        run: |
          yarn install
          yarn storybook:build

      - name: Push Storybook to GH pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: storybook-static
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
